---
- name: Create minecraft directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0770"
  loop:
    - /opt/minecraft

- name: Recursively change ownership of a directory, minecraft
  ansible.builtin.file:
    path: /opt/minecraft
    state: directory
    recurse: true
    owner: minecraft
    group: minecraft
