---
# https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html

- name: Add NVIDIA Container Toolkit repository
  ansible.builtin.get_url:
    url: https://nvidia.github.io/libnvidia-container/stable/rpm/nvidia-container-toolkit.repo
    dest: /etc/yum.repos.d/nvidia-container-toolkit.repo
    mode: "0644"

- name: Update DNF cache
  ansible.builtin.dnf:
    update_cache: true

- name: Install NVIDIA Container Toolkit packages
  ansible.builtin.dnf:
    name:
      - "nvidia-container-toolkit-{{ configure_nvidia_container_tools_version }}"
      - "nvidia-container-toolkit-base-{{ configure_nvidia_container_tools_version }}"
      - "libnvidia-container-tools-{{ configure_nvidia_container_tools_version }}"
      - "libnvidia-container1-{{ configure_nvidia_container_tools_version }}"
    state: present
  notify:
    - Configure nvidia-ctk docker runtime
    - Restart docker service
