---
- name: Setup cert host
  hosts: bigbilly
  gather_facts: false
  become: true
  roles:
    # Preflight
    - maintenance_gather_facts

    # Onboard Server
    - meta_onboard

    # Configure Disks
    - configure_disks
