---
- name: Setup discord file server host
  hosts: df
  gather_facts: false
  become: true
  roles:
    # Preflight
    # - maintenance_gather_facts_pve
    # - create_opnsense_entries
    # - create_proxmox_ct
    - maintenance_gather_facts

    # Onboard Server
    - meta_onboard

    # Actual
    # - configure_nginx
    - configure_discord_file_server

    # End
    # - configure_telegraf
    # - configure_elastic_agent
