---
# - name: Setup nvidia driver on hosts
#   hosts: pvematt,kismnas,stream
#   gather_facts: true
#   become: true
#   roles:
#     # Preflight

#     # Configure Nvidia drivers
#     - configure_nvidia_driver

- name: Setup nvidia container tools on hosts
  hosts: stream
  gather_facts: true
  become: true
  roles:
    # Preflight

    # Configure Nvidia drivers
    - configure_nvidia_container_tools
