---
target_host_ip_address: 10.42.0.8
target_host_mac_address: 00:D0:F1:22:22:22
proxmox_target_node: pvematt
proxmox_ct_disk: "local-lvm:15"
proxmox_ct_memory: 2048
proxmox_ct_cores: 2
proxmox_ct_unprivileged: false
proxmox_ct_conf_extra: []
