---
target_host_ip_address: 10.42.0.12
target_host_mac_address: 00:D0:F1:55:55:55
proxmox_target_node: pvematt
proxmox_ct_disk: "local-lvm:15"
proxmox_ct_memory: 2048
proxmox_ct_cores: 2
proxmox_ct_unprivileged: false
proxmox_ct_conf_extra:
  - "lxc.cgroup2.devices.allow: c 10:200 rwm"
  - "lxc.mount.entry: /dev/net dev/net none bind,create=dir"
  - "lxc.cgroup2.devices.allow: c 195:* rwm"
  - "lxc.cgroup2.devices.allow: c 511:* rwm"
  - "lxc.cgroup2.devices.allow: c 236:* rwm"
  - "lxc.mount.entry: /dev/nvidia0 dev/nvidia0 none bind,optional,create=file"
  - "lxc.mount.entry: /dev/nvidiactl dev/nvidiactl none bind,optional,create=file"
  - "lxc.mount.entry: /dev/nvidia-modeset dev/nvidia-modeset none bind,optional,create=file"
  - "lxc.mount.entry: /dev/nvidia-uvm dev/nvidia-uvm none bind,optional,create=file"
  - "lxc.mount.entry: /dev/nvidia-uvm-tools dev/nvidia-uvm-tools none bind,optional,create=file"
  - "lxc.mount.entry: /dev/nvidia-caps/nvidia-cap1 dev/nvidia-caps/nvidia-cap1 none bind,optional,create=file"
  - "lxc.mount.entry: /dev/nvidia-caps/nvidia-cap2 dev/nvidia-caps/nvidia-cap2 none bind,optional,create=file"
proxmox_ct_features:
  - nesting=true
