---
# MOTD, bash config
- name: Create motd directory
  ansible.builtin.file:
    path: /opt/motd
    state: directory
    mode: "0755"

- name: Copy motd file
  ansible.builtin.copy:
    src: files/motd.py
    dest: /opt/motd/motd.py
    mode: "0644"

- name: Create cron job for motd
  ansible.builtin.cron:
    name: "Update MOTD every day"
    minute: "25"
    hour: "0"
    job: "/usr/bin/python3 /opt/motd/motd.py > /etc/motd"
