---
configure_packages_to_install:
  - lm_sensors
  - ffmpeg
  - pacman-contrib # for pactree
  - terminus-font
  # Graphical applications
  - firefox
  - avahi
  - hwinfo
  - blueman # bluetooth manager
  # Fonts
  - noto-fonts
  - noto-fonts-cjk
  - noto-fonts-emoji
  - noto-fonts-extra

configure_packages_to_remove: []
