---
- name: Ensure old repo listing is removed {{ ansible_facts["distribution"] + ansible_facts["pkg_mgr"] }}
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/influxdata.list
    state: absent

- name: Ensure old apt key is removed {{ ansible_facts["distribution"] + ansible_facts["pkg_mgr"] }}
  ansible.builtin.file:
    path: /etc/apt/keyrings/influxdata-archive.key
    state: absent

- name: Add Telegraf repository {{ ansible_facts['distribution'] | lower }}
  ansible.builtin.deb822_repository:
    name: influxdata
    types: deb
    uris: https://repos.influxdata.com/{{ ansible_facts['distribution'] | lower }}
    suites: stable
    components: main
    architectures:
      - amd64
      - arm64
    signed_by: https://repos.influxdata.com/influxdata-archive.key
    install_python_debian: true
    state: present
