---
- name: Remove old yum repo
  ansible.builtin.file:
    path: /etc/yum.repos.d/influxdb.repo
    state: absent

- name: Copy over influxdata repo
  ansible.builtin.copy:
    src: files/influxdata.repo
    dest: /etc/yum.repos.d/influxdata.repo
    mode: "644"

- name: Install telegraf
  ansible.builtin.dnf:
    name: telegraf
    state: present
