---
- name: Remove old yum repo {{ ansible_facts["distribution"] + ansible_facts["pkg_mgr"] }}
  ansible.builtin.file:
    path: /etc/yum.repos.d/influxdb.repo
    state: absent

- name: Copy over influxdata repo {{ ansible_facts["distribution"] + ansible_facts["pkg_mgr"] }}
  ansible.builtin.copy:
    src: files/influxdata.repo
    dest: /etc/yum.repos.d/influxdata.repo
    mode: "644"

- name: Install telegraf {{ ansible_facts["distribution"] + ansible_facts["pkg_mgr"] }}
  ansible.builtin.dnf:
    name: telegraf
    state: present
