---
- name: Install packages for samba {{ ansible_distribution + " " + distribution_major_version }}
  ansible.builtin.apt:
    name:
      - samba
      - samba-vfs-modules
      - rsync
      - wsdd2
      - avahi-daemon
    state: present
  notify:
    - Print smb reminder

- name: Start and enable services {{ ansible_distribution + " " + distribution_major_version }}
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    enabled: true
  loop:
    - smbd
    - wsdd2
    - avahi-daemon
  notify:
    - Print smb reminder

- name: Allow samba and wsdd through firewalld {{ ansible_distribution + " " + distribution_major_version }}
  ansible.posix.firewalld:
    service: "{{ item }}"
    zone: public
    permanent: true
    state: enabled
  notify:
    - Reload firewalld
  loop:
    - samba
    - wsdd
    - mdns
