---
- name: Create dir for docker compose
  ansible.builtin.file:
    path: /opt/dispatcharr
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Copy docker compose file
  ansible.builtin.copy:
    src: files/docker-compose.yml
    dest: /opt/dispatcharr/docker-compose.yml
    owner: root
    group: root
    mode: "0644"

- name: Allow dispatcharr through firewall
  ansible.posix.firewalld:
    service: dispatcharr
    permanent: true
    state: enabled
    immediate: true

- name: Allow AceStream through firewall
  ansible.posix.firewalld:
    service: acestream
    permanent: true
    state: enabled
    immediate: true

- name: Allow AceReStreamer through firewall
  ansible.posix.firewalld:
    service: acerestreamer
    permanent: true
    state: enabled
    immediate: true

- name: Allow Prometheus Exporter
  ansible.posix.firewalld:
    service: prometheus-exporter
    permanent: true
    state: enabled
    immediate: true
