---
- name: Configure nvidia-ctk docker runtime
  ansible.builtin.command:
    cmd: nvidia-ctk runtime configure --runtime=docker
  changed_when: true

- name: Restart docker service
  ansible.builtin.systemd_service:
    name: docker
    state: restarted
