---
# Set up NVIDIA network repository for Oracle Linux
# https://docs.nvidia.com/drivers/

- name: Install kernel headers
  ansible.builtin.package:
    name:
      - "kernel-devel-{{ ansible_facts['kernel'] }}"
      - kernel-headers
    state: present

- name: Enable CodeReady Builder repository (OL9)
  ansible.builtin.command:
    cmd: dnf config-manager --set-enabled ol9_codeready_builder
  changed_when: false # Idempotent operation
  when: ansible_facts['distribution_major_version'] == '9'

- name: Enable CodeReady Builder repository (OL8)
  ansible.builtin.command:
    cmd: dnf config-manager --set-enabled ol8_codeready_builder
  changed_when: false # Idempotent operation
  when: ansible_facts['distribution_major_version'] == '8'

- name: Install EPEL (OL9)
  ansible.builtin.package:
    name: oracle-epel-release-el9
    state: present
  when: ansible_facts['distribution_major_version'] == '9'

- name: Install EPEL (OL8)
  ansible.builtin.package:
    name: oracle-epel-release-el8
    state: present
  when: ansible_facts['distribution_major_version'] == '8'

- name: Set distro string for NVIDIA repo
  ansible.builtin.set_fact:
    configure_nvidia_driver_new_distro: "ol{{ ansible_facts['distribution_major_version'] }}"

- name: Add NVIDIA repository (x86_64)
  ansible.builtin.command:
    cmd: >-
      dnf config-manager
      --add-repo https://developer.download.nvidia.com/compute/cuda/repos/{{ configure_nvidia_driver_new_distro }}/x86_64/cuda-{{ configure_nvidia_driver_new_distro }}.repo
    creates: /etc/yum.repos.d/cuda-{{ configure_nvidia_driver_new_distro }}.repo
  when: ansible_architecture == "x86_64"

- name: Add NVIDIA repository (arm64)
  ansible.builtin.command:
    cmd: >-
      dnf config-manager
      --add-repo https://developer.download.nvidia.com/compute/cuda/repos/{{ configure_nvidia_driver_new_distro }}/sbsa/cuda-{{ configure_nvidia_driver_new_distro }}.repo
    creates: /etc/yum.repos.d/cuda-{{ configure_nvidia_driver_new_distro }}.repo
  when: ansible_architecture == "aarch64"

- name: Clean dnf cache
  ansible.builtin.command:
    cmd: dnf clean all
  changed_when: false

- name: Enable dnf module stream for open kernel modules
  ansible.builtin.command:
    cmd: dnf module enable nvidia-driver:open-dkms -y
  changed_when: false # Idempotent operation
  when: configure_nvidia_driver_new_kernel_modules == "open"

- name: Enable dnf module stream for proprietary kernel modules
  ansible.builtin.command:
    cmd: dnf module enable nvidia-driver:latest-dkms -y
  changed_when: false # Idempotent operation
  when: configure_nvidia_driver_new_kernel_modules == "proprietary"
