---
# Host installation - full driver with kernel modules

- name: Install NVIDIA driver (open kernel modules)
  ansible.builtin.package:
    name:
      - nvidia-open
    state: present
  when: configure_nvidia_driver_new_kernel_modules == "open"

- name: Install NVIDIA driver (proprietary kernel modules)
  ansible.builtin.package:
    name:
      - cuda-drivers
    state: present
  when: configure_nvidia_driver_new_kernel_modules == "proprietary"

- name: Set to load nvidia modules into the kernel
  ansible.builtin.copy:
    src: files/nvidia-modules.conf
    dest: /etc/modules-load.d/nvidia-modules.conf
    mode: "0600"

- name: Set to load nvidia udev rules
  ansible.builtin.copy:
    src: files/70-nvidia.rules
    dest: /etc/udev/rules.d/70-nvidia.rules
    mode: "0600"

- name: Enable nvidia-persistenced service
  ansible.builtin.systemd_service:
    service: nvidia-persistenced
    enabled: true
    state: started
