---
# https://docs.nvidia.com/drivers/
# Installs NVIDIA drivers using NVIDIA's official repositories

- name: Check if nouveau is loaded
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      lsmod | grep ^nouveau
  changed_when: false # Just getting info
  failed_when: false # Just getting info
  register: configure_nvidia_driver_new_nouveau_loaded

- name: Copy nouveau blocklist
  ansible.builtin.copy:
    src: files/blocklist-nouveau.conf
    dest: /etc/modprobe.d/blocklist-nouveau.conf
    mode: "0600"
  register: configure_nvidia_driver_new_blocklist_copy

- name: Blacklist nouveau and reboot if needed
  when: configure_nvidia_driver_new_nouveau_loaded.rc == 0 and ansible_facts['virtualization_role'] == 'host'
  block:
    - name: Run initramfs update
      ansible.builtin.command:
        cmd: update-initramfs -u
      changed_when: configure_nvidia_driver_new_blocklist_copy.changed

    - name: Reboot
      ansible.builtin.reboot:

- name: Wait for everything to come back
  ansible.builtin.wait_for_connection:
    timeout: 600

- name: Set up NVIDIA repository and install prerequisites
  ansible.builtin.include_tasks: "01-{{ ansible_pkg_mgr }}.yml"

- name: Install NVIDIA driver
  ansible.builtin.include_tasks: "02-{{ ansible_facts['virtualization_role'] }}.yml"
