---
- name: Configure the opnsense acme client
  delegate_to: localhost
  become: false
  module_defaults:
    group/oxlorg.opnsense.all:
      firewall: "{{ opnsense_firewall }}"
      api_key: "{{ secret_opnsense_api_key }}"
      api_secret: "{{ secret_opnsense_api_secret }}"
      ssl_verify: false
  block:
    - name: Enable the acme client plugin
      oxlorg.opnsense.acme_general:
        enabled: true
        auto_renewal: true

    - name: Ensure that the acme account exists
      oxlorg.opnsense.acme_account:
        name: "{{ configure_opnsense_acme_account_name }}"
        description: "Let's Encrypt"
        email: "{{ secret_email }}"
        ca: letsencrypt
        register: true

    - name: Ensure that the dns-01 validation exists
      oxlorg.opnsense.acme_validation:
        name: "{{ configure_opnsense_acme_validation_name }}"
        description: "DNS-01 via Cloudflare"
        method: dns01
        dns_service: dns_cf
        dns_cf_token: "{{ secret_cloudflare_api_dns }}"
        dns_cf_account_id: "{{ secret_cloudflare_account_id }}"
        dns_sleep: 30

    - name: Ensure that there is an action to restart the gui after renewal
      oxlorg.opnsense.acme_action:
        name: "{{ configure_opnsense_acme_action_name }}"
        description: "Restart the OPNsense GUI"
        type: configd_restart_gui

    # This only creates the cert config, the first issuance is a button in the WebUI
    - name: Ensure that the certificates exist
      oxlorg.opnsense.acme_certificate:
        name: "{{ item.name }}"
        description: "{{ item.description | default(item.name) }}"
        alt_names: "{{ item.alt_names | default(omit) }}"
        account: "{{ configure_opnsense_acme_account_name }}"
        validation: "{{ configure_opnsense_acme_validation_name }}"
        restart_actions: ["{{ configure_opnsense_acme_action_name }}"]
        key_length: "{{ item.key_length | default('key_4096') }}"
      loop: "{{ configure_opnsense_acme_certificates }}"
      loop_control:
        label: "{{ item.name }}"
