---
name: ansible-taste
on:
  push:
    branches:
      - main

jobs:
  taste:
    name: Ansible Taste
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-python@v7

      - name: Run ansible-taste
        run: pipx run git+https://github.com/kism/ansible-taste
